### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by rgoalcast** [MAVENSDC/Pydivide#23]
I am new to Pydivide, How can I correct IndexError? 

insitu, iuvs = pydivide.read('2015-12-25')
Traceback (most recent call last):

  File "<ipython-input-8-28e799caa4f4>", line 1, in <module>
    insitu, iuvs = pydivide.read('2015-12-25')

  File "/Users/username/opt/anaconda3/lib/python3.8/site-packages/pydivide/read.py", line 77, in read
    date = re.findall(r'_(\d{8})', file)[0]

IndexError: list index out of range

**Comment by bryan-harter** [comment]
The correct way to read in a specific date would be to type:

insitu, iuvs = pydivide.read(input_time = '2015-12-25')

I believe some of the documentation is outdated, sorry if the docs refer to the other way you tried to call the function.  

Also, try updating your version of pydivide to solve the other error.  It looks like you added in an incorrect indent in your code when you tried to fix the spedas_data_dir issues.

**Comment by rgoalcast** [comment]
I am trying this
pydivide.download_files(start_date='2015-12-25', end_date='2015-12-31', insitu=True, list_files=True, new_files=True)
got this in output
mvn_kp_insitu_20151231_v15_r05.tab
mvn_kp_insitu_20151230_v15_r05.tab
mvn_kp_insitu_20151229_v15_r05.tab
mvn_kp_insitu_20151228_v15_r05.tab
mvn_kp_insitu_20151227_v15_r05.tab
mvn_kp_insitu_20151226_v15_r05.tab
mvn_kp_insitu_20151225_v15_r05.tab

But, during read 
insitu, iuvs = pydivide.read(input_time = '2015-12-25')
No files found for the input date range, and no specific filenames were given. Exiting.
Traceback (most recent call last):

  File "<ipython-input-11-a81a71b29dae>", line 1, in <module>
    insitu, iuvs = pydivide.read(input_time = '2015-12-25')

TypeError: cannot unpack non-iterable NoneType object

How can I correct error?
